name: CI devops 2022 test
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [ origin, dev ]
  pull_request:

jobs:
  # Use the docker.yml file and the backend_test.yml file to do the CI/CD

  back_end_tests:
    uses: ./.github/workflows/backend_test.yml
    with:
      project_key: 'JiaenLiu123_simple-api-student'
      organization: 'jiaenliu123'
      pom_path: './pom.xml'
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}